# Git command-specific aliases
alias add="git add"
alias addall="git add -A"
alias fetch="git fetch --all --prune"
alias move="git mv"
alias reset="git reset --hard"
alias stash="git stash"
alias status="echo ${O}; git status; echo ${X}"
alias unstash="git stash apply"
alias untrack="git rm"
