# Massive resets for when major changes occur to the working tree or variables.
export GIT_INSTALL=""
export GIT_BIN=""
export GIT_ETC=""
export gitscripts_path=""
export native_bash_profile_path=""
export gitscripts_motd_path=""
export native_motd_path=""
export inputdir=""
export outputdir=""
export awkdir=""
export tempdir=""
export tmp=""
export flscripts_temp_bash_profile_path=""
echo "Variables reset!"